[versions]
resourcesVersion = "0.21.2+apter.build.1"

[libraries]
resources = { module = "tech.apter.moko:resources", version.ref = "resourcesVersion" }
resourcesCompose = { module = "tech.apter.moko:resources-compose", version.ref = "resourcesVersion" }
resourcesTest = { module = "tech.apter.moko:resources-test", version.ref = "resourcesVersion" }

resourcesGradlePlugin = { module = "tech.apter.moko:resources-generator", version.ref = "resourcesVersion" }
